services:
  # A Docker web service
  - type: web
    name: server
    env: docker
    branch: main # optional (defaults to master)
    rootDir: server
    dockerCommand: ./start.sh # optional (defaults to Dockerfile command)
    numInstances: 3
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host # available properties are listed below
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
  # A static site
  - type: web
    name: client
    env: static
    buildCommand: cd client && yarn && yarn build
    staticPublishPath: ./client/dist
    pullRequestPreviewsEnabled: true # optional
    buildFilter:
      paths:
        - client/src/**/*.js
      ignoredPaths:
        - client/src/**/*.test.js
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a
  # A Redis instance
  - type: redis
    name: lightning
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # optional (defaults to starter)
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)
